#PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/compte
spring.datasource.username=jerome
spring.datasource.password=jerome

spring.jpa.properties.hibernate.default_schema=banque
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
