#Global configuration
spring.application.name=api

#Tomcat configuration
server.port=9000

#Log level configuration
logging.level.root=INFO
logging.level.com.banque=INFO
logging.level..org.springframework.web.embedded.tomcat=INFO

#Database configuration
spring.jpa.hibernate.ddl-auto=update

#Profile configuration
spring.profiles.active=h2
