#Global Configuration
spring.application.name=webapp

#Tomcat configuration
server.port=9001

#Log level Configuration
logging.level.root=INFO
logging.level.com.banque.compte=INFO
logging.level.org.springframework.boot.web.embedded.tomcat=INFO

#Custom Configuration
com.banque.compte.webapp.configuration.apiUrl = http://localhost:9000